---
- name: Ensure group consul exists
  group:
    name: consul
    state: present

- name: Create consul user
  user:
    state: present
    name: consul
    system: yes
    group: consul
    password: consul
    create_home: yes
    home: /etc/consul.d
    shell: /bin/bash

- name: Copy config file
  template: 
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

- name: Ensure consul data dir is configured correctly
  file:
    path: /opt/consul
    owner: consul
    state: directory

- name: Create consul service file
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Enable and start systemd consul service
  systemd:
    name: consul
    state: started
    enabled: yes

- name: Ensure consul acl system is ready
  shell: |
    consul acl policy list &> /dev/null
    VALUE=$?
    echo "Waiting until consul's ACL system is ready"
    while [ $VALUE -ne 0 ]; do
      consul acl policy list &> /dev/null
      VALUE=$?
    done
  args:
    executable: /bin/bash
  environment:
        CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"

- name: Ensure consul policies dir is configured correctly
  file:
    path: "{{ consul_home_directory }}policies"
    owner: consul
    state: directory

- name: Ensure scripts dir is configured correctly
  file:
    path: "{{ consul_home_directory }}scripts"
    owner: consul
    state: directory

- name: Copy all policy files from module files to target
  copy:
    src: "{{ item }}"
    dest: "{{ consul_home_directory }}policies/"
  with_fileglob:
    - files/policies/*

- name: Copy all scripts to consul_home
  copy:
    src: "{{ item }}"
    dest: "{{ consul_home_directory }}scripts/"
  with_fileglob:
    - files/scripts/*
