---
- name: Update yum
  yum: update_cache=yes

- name: Ensure unzip is installed
  yum: name=unzip state=installed

- name: Ensure consul is installed
  unarchive: 
    src: https://releases.hashicorp.com/consul/1.7.1/consul_1.7.1_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: Ensure group consul exists
  group:
    name: consul
    state: present

- name: Create consul user
  user:
    name: consul
    system: yes
    group: consul
    password: consul
    create_home: yes
    home: /etc/consul.d
    shell: /bin/bash

- name: Create config file
  template: 
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

- name: Ensure consul data dir is configured correctly
  file:
    path: /opt/consul
    owner: consul
    state: directory

- name: Create consul service file
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Enable and start systemd consul service
  systemd:
    name: consul
    state: started
    enabled: yes

- name: Ensure consul acl system is ready
  shell: |
    consul acl policy list &> /dev/null
    VALUE=$?
    echo "Waiting until consul's ACL system is ready"
    while [ $VALUE -ne 0 ]; do
      consul acl policy list &> /dev/null
      VALUE=$?
    done
  args:
    executable: /bin/bash
  environment:
        CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"

- name: Ensure consul policies dir is configured correctly
  file:
    path: /opt/consul/policies
    owner: consul
    state: directory

- name: Ensure agent policy file is present
  copy: 
    src: agent-policy.hcl
    dest: /opt/consul/policies/agent-policy.hcl

- name: Create consul agent policy
  shell: consul acl policy create -name "consul-agent-policy" -description "Consul agent policy" -rules @/opt/consul/policies/agent-policy.hcl 
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
  ignore_errors: True

- name: Create consul agent token
  shell: consul acl token create -description "Consul agent token" -policy-name "consul-agent-policy" | grep -Po 'SecretID:\s*\K[0-9a-z-]*'
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
  register: consul_agent_token

- name: Add consul agent token for {{ ansible_default_ipv4.address }}
  aws_secret:
    name: 'consul_agent_token'
    state: present
    secret_type: 'string'
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    region: "{{ AWS_REGION }}"
    secret: "{{ consul_agent_token.stdout }}"
  become: yes
  become_user: "{{ AWS_HOST_USER }}"
  delegate_to: localhost
