---
- name: Update yum
  yum: update_cache=yes

- name: Ensure unzip is installed
  yum: name=unzip state=installed

- name: Ensure consul is installed
  unarchive: 
    src: https://releases.hashicorp.com/consul/1.7.1/consul_1.7.1_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: Ensure group consul exists
  group:
    name: consul
    state: present

- name: Create consul user
  user:
    name: consul
    system: yes
    group: consul
    password: consul
    create_home: yes
    home: /etc/consul.d
    shell: /bin/bash

- name: Create config file
  template: 
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

- name: Ensure consul data dir is configured correctly
  file:
    path: /opt/consul
    owner: consul
    state: directory

- name: Create consul service file
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Enable and start systemd consul service
  systemd:
    name: consul
    state: started
    enabled: yes
