---
- name: Ensure the policy file for vault is present
  copy:
    src: vault-policy.hcl
    dest: /opt/consul/policies/vault-policy.hcl

- name: Ensure vault policy is present
  shell: consul acl policy create -name "vault-policy" -description "Vault policy" -rules @/opt/consul/policies/vault-policy.hcl 
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
  ignore_errors: True

- name: Create consul token for vault access
  shell: consul acl token create -description "Vault agent token" -policy-name "vault-policy" | grep -Po 'SecretID:\s*\K[0-9a-z-]*'
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_master_token }}"
  register: consul_token_for_vault

- name: Add consul vault token created in {{ ansible_default_ipv4.address }}
  aws_secret:
    name: 'vault_token'
    state: present
    secret_type: 'string'
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    region: "{{ AWS_REGION }}"
    secret: "{{ consul_token_for_vault.stdout }}"
  become: yes
  become_user: "{{ AWS_HOST_USER }}"
  delegate_to: localhost

