---
- name: Ensure vault user group is created
  group: 
    name: "{{ vault_group }}"
    state: present

- name: Ensure vault user is present
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/bin/bash"
    comment: "vault User"
    createhome: yes
    home: /etc/vault.d

- name: Install prerequisites
  yum:
    name: unzip
    update_cache: yes
    state: installed

- name: Download binary
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    checksum: "{{vault_checksum}}"
  register: vault_download

- name: "Unzip vault archive"
  unarchive:
    src: "{{ vault_download.dest }}"
    dest: /usr/local/bin
    copy: no
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: "Set vault binary capabilities"
  capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  #notify: systemd_reload

- name: config file
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: vault service
  systemd:
    name: vault
    state: started
    enabled: yes


- name: Initialise Vault operator
  shell: /usr/local/bin/vault operator init -format json
  environment:
    VAULT_ADDR: "http://0.0.0.0:8200"
  register: vault_init_results
  ignore_errors: true
  retries: 5
  delay: 10
  until: vault_init_results.rc == 0

- name: Parse output of vault init
  set_fact:
    vault_init_parsed: "{{ vault_init_results.stdout | from_json }}"
  ignore_errors: true

- name: Write hex recovery keys to aws secrets manager
  aws_secret:
    name: "vault_recovery_key_b64-{{ item.0 }}"
    state: present
    secret_type: string
    aws_secret_key: "{{ secret_access_key }}"
    aws_access_key: "{{ access_key_id }}"
    region: "{{ aws_region }}"
    secret: "{{ item.1 }}"
  with_indexed_items: "{{ vault_init_parsed.recovery_keys_hex }}"
  become: yes
  become_user: "{{ AWS_HOST_USER }}"
  delegate_to: localhost


- name: Add vault root token for {{ ansible_default_ipv4.address }}
  aws_secret:
    name: 'vault_root_token'
    state: present
    secret_type: 'string'
    aws_secret_key: "{{ secret_access_key }}"
    aws_access_key: "{{ access_key_id }}"
    region: "{{ aws_region }}"
    secret: "{{ vault_init_parsed.root_token }}"
  become: yes
  become_user: "{{ AWS_HOST_USER }}"
  delegate_to: localhost
  ignore_errors: true

#- name: Reading unseal key contents
  #command: cat {{item}}
  #register: unseal_keys
  #with_fileglob: "{{ unseal_keys_dir_output }}/*"
  #delegate_to: localhost
  #become: yes
  #become_user: "{{ AWS_HOST_USER }}"
  #become: no

#- name: Unseal vault with unseal keys
  #shell: |
    #/usr/local/bin/vault operator unseal {{ item.stdout }}
  #environment:
    #VAULT_ADDR: "http://0.0.0.0:8200"
  #with_items: "{{unseal_keys.results}}"
